!Application
name: app2
appPort: 9992
activities:
 - name: test1
   businessUnit: Page
   relocability: no
   serviceLevelObjective:
      cumulativeBusinessObjective: !amount '830 Page'
      basePrice: !amount '500 EUR'
      priceModifiers:
       - threshold: !amount '900 Page'
         modifier: !amount '1 EUR/Page'
       - threshold: !amount '830 Page'
         modifier: !amount '-1 EUR/Page'
   dataCenters:
    - dataCenterName: dctest1
      defaultWorkingMode: WM0
      workingModes:
      - name: WM0
        value: 0
        actuator:
         systemCommand: bin/localWMSwitch.sh WM0
        performanceLevels:
         - businessPerformance: !amount '0 Page/min'
           power: !amount '0 W'
        transitions:
        - target: WM1
          performanceCost: !amount '1 Page'
        - target: WM2
          performanceCost: !amount '2 Page'
        - target: WM3
          performanceCost: !amount '3 Page'
        resources:
        - !CFApplication
           name: frontend
           disk: 100
           ram: 100
           instances: 1
           defaultPower: !amount '10 W'
      - name: WM1
        value: 1
        actuator:
         systemCommand: bin/localWMSwitch.sh WM1
        performanceLevels:
        - businessPerformance: !amount '10 Page/min'
          power: !amount '100 W'
        transitions:
        - target: WM2
          performanceCost: !amount '1 Page'
        - target: WM3
          performanceCost: !amount '2 Page'
        resources:
        - !CFApplication
           name: frontend
           disk: 200
           ram: 200
           instances: 1
           defaultPower: !amount '10 W'
        - !CFApplication
           name: backend
           disk: 200
           ram: 200
           instances: 1
           defaultPower: !amount '10 W'
      - name: WM2
        value: 2
        actuator: 
         systemCommand: bin/localWMSwitch.sh WM2
        performanceLevels:
        - businessPerformance: !amount '20 Page/min'
          power: !amount '200 W'
        transitions:
        - target: WM3
          performanceCost: !amount '1 Page'
        resources:
        - !CFApplication
           name: frontend
           disk: 200
           ram: 200
           instances: 2
           defaultPower: !amount '10 W'
        - !CFApplication
           name: backend
           disk: 200
           ram: 200
           instances: 1
           defaultPower: !amount '10 W'
      - name: WM3
        value: 3
        actuator:
         systemCommand: bin/localWMSwitch.sh WM3
        performanceLevels:
        - businessPerformance: !amount '30 Page/min'
          power: !amount '300 W'
        resources:
        - !CFApplication
           name: frontend
           disk: 200
           ram: 200
           instances: 2 
           defaultPower: !amount '10 W'
        - !CFApplication
           name: backend
           disk: 200
           ram: 200
           instances: 2
           defaultPower: !amount '10 W'
