!Application
name: EASC-CSUC
activities:
- name: VideoTranscoding
  businessUnit: MB
  relocability: no
  serviceLevelObjectives:
  - cumulativeBusinessObjective: !amount '93600 MB'
    basePrice: !amount '30 EUR'
    priceModifiers:
    - threshold: !amount '93600 MB'
      modifier: !amount '0 EUR/MB'
    - threshold: !amount '0 MB'
      modifier: !amount '-0.0007 EUR/MB'
  dataCenters:
  - dataCenterName: csuc_barcelona
    defaultWorkingMode: "VTWM0"
    workingModes:
    - name: "VTWM0"
      value: 0
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VTWM0 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '0 MB/min'
        power: !amount '0 W'
      transitions:
      - target: VTWM1
        performanceCost: !amount '216 MB'
      - target: VTWM2
        performanceCost: !amount '498 MB'
      - target: VTWM3
        performanceCost: !amount '853 MB'
      - target: VTWM4
        performanceCost: !amount '1153 MB'
      resources: []
    - name: "VTWM1"
      value: 1
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VTWM1 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '29 MB/min'
        power: !amount '44 W'
      transitions:
      - target: VTWM2
        performanceCost: !amount '41 MB'
      - target: VTWM3
        performanceCost: !amount '110 MB'
      - target: VTWM4
        performanceCost: !amount '207 MB'
      resources: 
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
    - name: "VTWM2"
      value: 2
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VTWM2 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '64 MB/min'
        power: !amount '72 W'
      transitions:
      - target: VTWM3
        performanceCost: !amount '38 MB'
      - target: VTWM4
        performanceCost: !amount '110 MB'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
    - name: "VTWM3"
      value: 3
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VTWM3 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '102 MB/min'
        power: !amount '101 W'
      transitions:
      - target: VTWM4
        performanceCost: !amount '38 MB'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !VM 
        name: vtvm3
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
    - name: "VTWM4"
      value: 4
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VTWM4 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '137 MB/min'
        power: !amount '122 W'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM 
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm3
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm4
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
- name: VideoTranscodingImi
  businessUnit: MB
  relocability: no
  serviceLevelObjectives:
  - cumulativeBusinessObjective: !amount '84960 MB'
    basePrice: !amount '30 EUR'
    priceModifiers:
    - threshold: !amount '84960 MB'
      modifier: !amount '0 EUR/MB'
    - threshold: !amount '0 MB'
      modifier: !amount '-0.0007 EUR/MB'
  dataCenters:
  - dataCenterName: imi_barcelona
    defaultWorkingMode: "VT0"
    workingModes:
    - name: "VT0"
      value: 0
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VT0 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '0 MB/min'
        power: !amount '0 W'
      transitions:
      - target: VT1
        performanceCost: !amount '120 MB'
      - target: VT2
        performanceCost: !amount '260 MB'
      - target: VT3
        performanceCost: !amount '379 MB'
      - target: VT4
        performanceCost: !amount '630 MB'
      resources: []
    - name: "VT1"
      value: 1
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VT1 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '29 MB/min'
        power: !amount '28 W'
      transitions:
      - target: VT2
        performanceCost: !amount '38 MB'
      - target: VT3
        performanceCost: !amount '92 MB'
      - target: VT4
        performanceCost: !amount '220 MB'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
    - name: "VT2"
      value: 2
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VT2 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '59 MB/min'
        power: !amount '41 W'
      transitions:
      - target: VT3
        performanceCost: !amount '31 MB'
      - target: VT4
        performanceCost: !amount '104 MB'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
    - name: "VT3"
      value: 3
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VT3 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '84 MB/min'
        power: !amount '58 W'
      transitions:
      - target: VT4
        performanceCost: !amount '45 MB'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm3
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
    - name: "VT4"
      value: 4
      actuator:
        systemCommand: "bin/WMSwitch.sh VideoTranscoding VT4 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '120 MB/min'
        power: !amount '72 W'
      resources:
      - !VM
        name: vtvm1
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm2
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm3
        ram: !amount '2 GB'
        vCpus: 20
      - !VM
        name: vtvm4
        ram: !amount '2 GB'
        vCpus: 20
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
- name: WebCrawling
  businessUnit: Webs
  relocability: spreadable
  migrationPerformanceCost: !amount '0 Webs'
  serviceLevelObjectives:
  - cumulativeBusinessObjective: !amount '200000 Webs'
    basePrice: !amount '120 EUR'
    priceModifiers:
    - threshold: !amount '200000 Webs'
      modifier: !amount '0 EUR/Webs'
    - threshold: !amount '0 Webs'
      modifier: !amount '-0.012 EUR/Webs'
  dataCenters:
  - dataCenterName: csuc_barcelona
    defaultWorkingMode: "WCWM0"
    workingModes:
    - name: "WCWM0"
      value: 0
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WCWM0 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '0 Webs/min'
        power: !amount '0 W'
      transitions:
      - target: WCWM2
        performanceCost: !amount '257 Webs'
      - target: WCWM5
        performanceCost: !amount '709 Webs'
      - target: WCWM7
        performanceCost: !amount '1710 Webs'
      resources: []
    - name: "WCWM2"
      value: 2
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WCWM2 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '30 Webs/min'
        power: !amount '27 W'
      transitions:
      - target: WCWM5
        performanceCost: !amount '125 Webs'
      - target: WCWM7
        performanceCost: !amount '551 Webs'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
    - name: "WCWM5"
      value: 5
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WCWM5 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '64 Webs/min'
        power: !amount '27 W'
      transitions:
      - target: WCWM7
        performanceCost: !amount '249 Webs'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm3
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm4
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm5
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
    - name: "WCWM7"
      value: 7
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WCWM7 csuc_barcelona"
      performanceLevels:
      - businessPerformance: !amount '135 Webs/min'
        power: !amount '28 W'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm3
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm4
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm5
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm6
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm7
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: cluster01
      - !Server
        name: cluster00
      - !Server
        name: cluster03
      - !Server
        name: cluster02
  - dataCenterName: imi_barcelona
    defaultWorkingMode: "WC0"
    workingModes:
    - name: "WC0"
      value: 0
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WC0 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '0 Webs/min'
        power: !amount '0 W'
      transitions:
      - target: WC2
        performanceCost: !amount '158 Webs'
      - target: WC5
        performanceCost: !amount '589 Webs'
      - target: WC7
        performanceCost: !amount '1096 Webs'
      resources: []
    - name: "WC2"
      value: 2
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WC2 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '26 Webs/min'
        power: !amount '12 W'
      transitions:
      - target: WC5
        performanceCost: !amount '191 Webs'
      - target: WC7
        performanceCost: !amount '494 Webs'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
    - name: "WC5"
      value: 5
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WC5 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '78 Webs/min'
        power: !amount '12 W'
      transitions:
      - target: WC7
        performanceCost: !amount '147 Webs'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm3
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm4
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm5
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
    - name: "WC7"
      value: 7
      actuator:
        systemCommand: "bin/WMSwitch.sh WebCrawling WC7 imi_barcelona"
      performanceLevels:
      - businessPerformance: !amount '120 Webs/min'
        power: !amount '12 W'
      resources:
      - !VM
        name: wcvm0
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm1
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm2
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm3
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm4
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm5
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm6
        ram: !amount '1 GB'
        vCpus: 1
      - !VM
        name: wcvm7
        ram: !amount '1 GB'
        vCpus: 1
      - !Server
        name: dc4c-on1
      - !Server
        name: dc4c-on2
      - !Server
        name: dc4c-on3
