csuc_barcelona:
 credentials: user:password
 endpoint: http://sunstone:2633/RPC2
 url: http://localhost
 vtname: VTWM
 wcname: WCWM
 home: /home/ois
 rubyversion: ruby-2.1.2
 videotimage: ami-00000065
 patroip: 84.88.31.
 endpointone: http://sunstone:4568/
 padicatimage: ami-00000063
 piretriximage: ami-00000062
 piretrixip: hackmeplz
 piretrixport: 2122
 networkid: 2
 host1: cluster01
 host2: cluster00
 host1id: 6
 host2id: 3
 ipmi: false
 userecone: user
 passwordecone: password
 VideoTranscoding: VideoTranscoding
 WebCrawling: WebCrawling
imi_barcelona:
 credentials: user:password
 endpoint: http://sunstone:2633/RPC2
 url: http://10.0.200.23
 vtname: VT
 wcname: WC
 home: /home/dc4cities
 rubyversion: ruby-2.1.4
 videotimage: ami-00000061
 vtname: VT
 wcname: WC
 patroip: 10.0.200.
 endpointone: http://sunstone:4568/
 padicatimage: ami-00000062
 piretriximage: ami-00000063
 vtname: VT
 wcname: WC
 patroip: 10.0.200.
 piretrixip: 10.0.200.61
 piretrixport: 22
 networkid: 4
 host1: dc4c-on1
 host2: dc4c-on2
 host1id: 0
 host2id: 1
 ipmi: true
 host1ipmi: dc4c-ipmi1
 host2ipmi: dc4c-ipmi2
 userecone: user
 passwordecone: password
 VideoTranscoding: VideoTranscodingImi
 WebCrawling: WebCrawling
