!ServerConfig
servers:
 - name: cluster01
   pidle: !amount '140 W'
   ram:   !amount '31.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: cluster00
   pidle: !amount '140 W'
   ram:   !amount '42.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: cluster03
   pidle: !amount '140 W'
   ram:   !amount '42.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: cluster02
   pidle: !amount '130 W'
   ram:   !amount '21.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: dc4c-on1
   pidle: !amount '219 W'
   ram:   !amount '28.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: dc4c-on2
   pidle: !amount '219 W'
   ram:   !amount '28.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
 - name: dc4c-on3
   pidle: !amount '128 W'
   ram:   !amount '28.0 GB'
   disk:  !amount '100 GB'
   nbCpus: 80
