!Configuration
energyService: default
EASCName: EASC-IMI
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 8484
energisURL: hackmeplz
monitoringSamplingTime: !amount '300 s'
siteCode: imi_barcelona
